# Mongo collection names
USERS_COLLECTION = 'users'

# Endpoints
API_VERSION = 1
ENDPOINT_PREFIX = f'/api/v{API_VERSION}'

USER_ENDPOINT_PREFIX = 'user'
RECIPE_ENDPOINT_PREFIX = 'recipe'
SIGNUP_ENDPOINT = f'{ENDPOINT_PREFIX}/{USER_ENDPOINT_PREFIX}/signup'
LOGIN_ENDPOINT = f'{ENDPOINT_PREFIX}/{USER_ENDPOINT_PREFIX}/login'
RECIPE_ENDPOINT = f'{ENDPOINT_PREFIX}/{RECIPE_ENDPOINT_PREFIX}/recipe'
